import { Injectable } from '@angular/core';

import { AxieModel } from './axie.model';

@Injectable()
export class AxieMockService{
  data: Array<AxieModel> =
  [
  {
    class: "balık",
    card_title: "shelter",
    card_describe: "Kullanıldığı raunt bu kartı kullanan axieye Kritik Vuruş yapılmasını engeller",
    part_name: "hermit",
    attack_type: "destek",
    energy_cost: '1',
    damage: 0,
    shield: 115,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/critical-block.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-02.png"
  },
  {
    class: "balık",
    card_title: "scale dart",
    card_describe: "Hedef rakip Son Direniş durumundaysa bir kart çekersiniz",
    part_name: "blue moon",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 120,
    shield: 30,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/draw-card.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-04.png"
  },
  {
    class: "balık",
    card_title: "swift escape",
    card_describe: "Bu axie aldığı her saldırı için 2 raunt boyunca Hız Bonusu alır",
    part_name: "gold fish",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 110,
    shield: 20,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/speed-up.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-06.png"
  },
  {
    class: "balık",
    card_title: "shipwreck",
    card_describe: "Kalkanı kırılırsa bir sonraki saldırısı için Saldırı Bonusu alır",
    part_name: "sponge",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 60,
    shield: 90,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/attack-up.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-08.png"
  },
  {
    class: "balık",
    card_title: "aqua vitality",
    card_describe: "Bu axie kendini sahip olduğu her \"Anemone\" parçası için 50 Can Puanı iyileştirir",
    part_name: "anemon",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 80,
    shield: 40,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/self-heal.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-10.png"
  },
  {
    class: "balık",
    card_title: "spinal tap",
    card_describe: "Bu kartın yanında en az 2 kart kullanıldığında Eylemsiz rakibi hedef alır",
    part_name: "perch",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 100,
    shield: 20,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/prioritize.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-back-12.png"
  },
  {
    class: "balık",
    card_title: "shell jab",
    card_describe: "Eylemsiz Hedeflere %30 fazla hasar verir",
    part_name: "babylonia",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 100,
    shield: 50,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/raise-damage.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-02.png"
  },
  {
    class: "balık",
    card_title: "deep sea gore",
    card_describe: "Bu axie her saldırı yaptığında bu karttan aldığı Kalkan %30 artar",
    part_name: "teal shell",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 50,
    shield: 80,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/raise-shield.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-04.png"
  },
  {
    class: "balık",
    card_title: "clam slash",
    card_describe: "Yabani, Böcek ve Meka sınıfı hedeflere vurunca bir sonraki saldırıya Saldırı Bonusu alır",
    part_name: "clam shell",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 110,
    shield: 40,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/attack-up.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-06.png"
  },
  {
    class: "balık",
    card_title: "aquaponics",
    card_describe: "Bu axie kendini sahip olduğu her \"Anemone\" parçası için 50 Can Puanı iyileştirir",
    part_name: "anemone",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 80,
    shield: 40,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/self-heal.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-08.png"
  },
  {
    class: "balık",
    card_title: "hero's bane",
    card_describe: "Hedef rakibin Son Direnişini bitirir",
    part_name: "oranda",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 120,
    shield: 30,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/end-last-stand.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-10.png"
  },
  {
    class: "balık",
    card_title: "star shuriken",
    card_describe: "Hedef rakip bu saldırı ile öldüğü zaman Son Direniş durumuna geçemez",
    part_name: "shoal star",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 115,
    shield: 10,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/end-last-stand.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-horn-12.png"
  },
  {
    class: "balık",
    card_title: "angry lam",
    card_describe: "Bu axienin Can Puanı %50nin altında ise %20 fazla hasar verir",
    part_name: "lam",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 110,
    shield: 40,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/raise-damage.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-mouth-02.png"
  },
  {
    class: "balık",
    card_title: "swallow",
    card_describe: "Axie kendini bu kartla rakibe verdiği hasar kadar iyileştirir",
    part_name: "catfish",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 80,
    shield: 30,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/self-heal.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-mouth-04.png"
  },
  {
    class: "balık",
    card_title: "fish hook",
    card_describe: "Bitki, Sürüngen ve Alacakaranlık sınıfı hedeflere vurunca bir sonraki saldırıya Saldırı Bonusu alır",
    part_name: "risky fish",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 110,
    shield: 30,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/attack-up.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-mouth-08.png"
  },
  {
    class: "balık",
    card_title: "crimson water",
    card_describe: "Bu axienin Can Puanı %50nin altında ise saldırı daha önce hasar almış rakip axieyi hedef alır",
    part_name: "piranha",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 120,
    shield: 30,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/prioritize.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-mouth-10.png"
  },
  {
    class: "balık",
    card_title: "upstream swim",
    card_describe: "Başka bir Balık kartıyla birlikte kullanıldığında bir sonraki raunt Hız Bonusu alır",
    part_name: "koi",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 110,
    shield: 30,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/speed-up.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-02.png"
  },
  {
    class: "balık",
    card_title: "tail swap",
    card_describe: "Başka bir kartla birlikte kullanıldığında 1 Enerji alırsınız",
    part_name: "nimo",
    attack_type: "yakından",
    energy_cost: '0',
    damage: 30,
    shield: 0,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/gain-energy.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-04.png"
  },
  {
    class: "balık",
    card_title: "black bubble",
    card_describe: "Hedefe 2 raunt için Şanssız efekti uygular",
    part_name: "tadpole",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 100,
    shield: 40,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/jinx.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-06.png"
  },
  {
    class: "balık",
    card_title: "water sphere",
    card_describe: "Hedefe 2 raunt için Soğuk efekti uygular",
    part_name: "ranchu",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 110,
    shield: 30,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/chill.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-08.png"
  },
  {
    class: "balık",
    card_title: "flanking smack",
    card_describe: "Bu axie ilk Saldırıyorsa %20 fazla hasar verir",
    part_name: "navaga",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 100,
    shield: 40,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/raise-damage.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-10.png"
  },
  {
    class: "balık",
    card_title: "chitin jump",
    card_describe: "En uzak rakibi hedef alır",
    part_name: "shrimp",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 30,
    shield: 30,
    icon_url: "https://storage.googleapis.com/axie-cdn/game/cards/effect-icons/prioritize.png",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/aquatic-tail-12.png"
  },
  {
    class: "yabani",
    card_title: "single combat",
    card_describe: "Bu kartın yanında en az 2 kart kullanıldığında bu kart garanti Kritik Vuruş yapar",
    part_name: "ronin",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-02.png"
  },
  {
    class: "yabani",
    card_title: "heroic reward",
    card_describe: "Balık, Kuş ve Şafak sınıfı axieye hasar verirse 1 kart çekersiniz",
    part_name: "hero",
    attack_type: "yakından",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-04.png"
  },
  {
    class: "yabani",
    card_title: "nitro leap",
    card_describe: "Bu kart Son Direniş durumunda kullanıldıysa bu axie diğer axielerden önce saldırır",
    part_name: "jaguar",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-06.png"
  },
  {
    class: "yabani",
    card_title: "revenge arrow",
    card_describe: "Son Direniş durumunda %50 fazla hasar verir",
    part_name: "risky beast",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-08.png"
  },
  {
    class: "yabani",
    card_title: "woodman power",
    card_describe: "Bu axie Bitki sınıfı rakibe vurduğu hasar kadar Kalkan alır",
    part_name: "timber",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-10.png"
  },
  {
    class: "yabani",
    card_title: "juggling balls",
    card_describe: "Bu kart ile 3 defa saldırı yapar",
    part_name: "furball",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-back-12.png"
  },
  {
    class: "yabani",
    card_title: "branch charge",
    card_describe: "Bitki sınıfı bir kartla birlikte kullanıldığında Kritik Vuruş şansını %20 arttırır",
    part_name: "little branch",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-02.png"
  },
  {
    class: "yabani",
    card_title: "ivory stab",
    card_describe: "Takımının bu raunt yaptığı her Kritik Vuruş için 1 enerji alırsınız",
    part_name: "imp",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-04.png"
  },
  {
    class: "yabani",
    card_title: "merry legion",
    card_describe: "Zincirleme Saldırı yapılırsa %20 fazla kalkan alır",
    part_name: "merry legion",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-06.png"
  },
  {
    class: "yabani",
    card_title: "sugar rush",
    card_describe: "Takımındaki her Böcek sınıfı axie için %10 hasar bonusu alır",
    part_name: "pocky",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-08.png"
  },
  {
    class: "yabani",
    card_title: "sinister strike",
    card_describe: "Kritik Vuruşlar 2.5 kat hasar verir",
    part_name: "dual blade",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-10.png"
  },
  {
    class: "yabani",
    card_title: "acrobatic",
    card_describe: "Saldırı yaptığında bir sonraki raunt Hız Bonusu alır",
    part_name: "arco",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-horn-12.png"
  },
  {
    class: "yabani",
    card_title: "nut crack",
    card_describe: "Başka bir \"Nut Cracker\" kartıyla kullanıldığında %20 fazla hasar verir",
    part_name: "nut cracker",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-mouth-02.png"
  },
  {
    class: "yabani",
    card_title: "piercing sound",
    card_describe: "Rakibin 1 enerjisini yok eder",
    part_name: "goda",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-mouth-04.png"
  },
  {
    class: "yabani",
    card_title: "death mark",
    card_describe: "Bu axienin Can Puanı %30un altındaysa rakibe Ölümcül efekti uygular",
    part_name: "axie kiss",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-mouth-08.png"
  },
  {
    class: "yabani",
    card_title: "self rally",
    card_describe: "Bu axieye 2 raunt boyunca Moral Bonusu uygular",
    part_name: "confident",
    attack_type: "destek",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-mouth-10.png"
  },
  {
    class: "yabani",
    card_title: "luna absorb",
    card_describe: "1 enerji alırsınız",
    part_name: "cottontail",
    attack_type: "destek",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-02.png"
  },
  {
    class: "yabani",
    card_title: "night steal",
    card_describe: "Başka bir kart ile birlikte kullanıldığında rakipten 1 enerji çalar",
    part_name: "rice",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-04.png"
  },
  {
    class: "yabani",
    card_title: "rampant howl",
    card_describe: "Bu kart Son Direniş durumunda kullanılırsa takımına 2 raunt boyunca Moral bonusu verir",
    part_name: "shiba",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-06.png"
  },
  {
    class: "yabani",
    card_title: "hare dagger",
    card_describe: "Bu axie raunt başında ilk saldırıyı yapıyorsa 1 kart çekersiniz",
    part_name: "hare",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-08.png"
  },
  {
    class: "yabani",
    card_title: "nut throw",
    card_describe: "Başka bir \"Nut Cracker\" kartıyla kullanıldığında %20 fazla hasar verir",
    part_name: "nut cracker",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-10.png"
  },
  {
    class: "yabani",
    card_title: "gerbil jump",
    card_describe: "İkiden fazla rakip varsa en yakındakini atlayıp arkasındaki rakibi hedef alır",
    part_name: "gerbil",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/beast-tail-12.png"
  },
  {
    class: "kuş",
    card_title: "balloon pop",
    card_describe: "İkiden fazla rakip varsa en yakındakini atlayıp arkasındaki rakibi hedef alır",
    part_name: "balloon",
    attack_type: "uzaktan",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-02.png"
  },
  {
    class: "kuş",
    card_title: "heart break",
    card_describe: "Hedef rakibe 2 raunt için Negatif Moral efekti uygular",
    part_name: "cupid",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-04.png"
  },
  {
    class: "kuş",
    card_title: "ill-omened",
    card_describe: "Hedef rakibe 2 raunt için Şanssız efekti uygular",
    part_name: "raven",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-06.png"
  },
  {
    class: "kuş",
    card_title: "blackmail",
    card_describe: "Bu axie üzerindeki negatif efektleri rakibe aktarır",
    part_name: "pigeon post",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-08.png"
  },
  {
    class: "kuş",
    card_title: "patient hunter",
    card_describe: "Bu axienin Can Puanı %50nin altındaysa Balık sınıfı rakibi hedef alır",
    part_name: "kingfisher",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-10.png"
  },
  {
    class: "kuş",
    card_title: "triple threat",
    card_describe: "Bu axienin üzerinde negatif bir efekt varsa bu kartla iki kere saldırır",
    part_name: "tri feather",
    attack_type: "uzaktan",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-back-12.png"
  },
  {
    class: "kuş",
    card_title: "eggbomb",
    card_describe: "Bu axie kendine bir sonraki raunta kadar Aroma efekti uygular",
    part_name: "eggshell",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-02.png"
  },
  {
    class: "kuş",
    card_title: "cockadoodledoo",
    card_describe: "Bir sonraki saldırı için Saldırı Bonusu alır",
    part_name: "cuckoo",
    attack_type: "uzaktan",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-04.png"
  },
  {
    class: "kuş",
    card_title: "air force one",
    card_describe: "Başka bir \"Trump\" kartıyla birlikte kullanıldığında %20 fazla hasar verir",
    part_name: "trump",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-06.png"
  },
  {
    class: "kuş",
    card_title: "headshot",
    card_describe: "Rakibin bir sonraki raunt Boynuz kartını kullanmasını engeller",
    part_name: "kestrel",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-08.png"
  },
  {
    class: "kuş",
    card_title: "smart shot",
    card_describe: "İkiden fazla rakip varsa en yakındakini atlayıp arkasındaki rakibi hedef alır",
    part_name: "wing horn",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-10.png"
  },
  {
    class: "kuş",
    card_title: "feather lunge",
    card_describe: "Başka bir \"Lunge\" kartıyla Zincirleme Saldırı yapıldığında %20 fazla hasar verir",
    part_name: "feather spear",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-horn-12.png"
  },
  {
    class: "kuş",
    card_title: "soothing song",
    card_describe: "Hedef rakibin kalkanını baypas eder ve Uykulu efekti uygular",
    part_name: "doubletalk",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-mouth-02.png"
  },
  {
    class: "kuş",
    card_title: "peace treaty",
    card_describe: "Hedef rakibe Negatif Saldırı efekti uygular",
    part_name: "peace maker",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-mouth-04.png"
  },
  {
    class: "kuş",
    card_title: "insectivore",
    card_describe: "Bu axienin Can Puanı %50nin altındaysa Böcek sınıfı rakibi hedef alır",
    part_name: "hungry bird",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-mouth-08.png"
  },
  {
    class: "kuş",
    card_title: "dark swoop",
    card_describe: "En hızlı rakibi hedef alır",
    part_name: "little owl",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-mouth-10.png"
  },
  {
    class: "kuş",
    card_title: "early bird",
    card_describe: "Bu axie raunt başında ilk saldırıyı yapıyorsa %20 fazla hasar verir",
    part_name: "swallow",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-02.png"
  },
  {
    class: "kuş",
    card_title: "sunder armor",
    card_describe: "Bu axie üzerindeki her negatif efekt için %20 fazla kalkan alır",
    part_name: "feather fan",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-04.png"
  },
  {
    class: "kuş",
    card_title: "risky feather",
    card_describe: "Bu axie kendine 2x Negatif Saldırı efekti uygular",
    part_name: "the last one",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-06.png"
  },
  {
    class: "kuş",
    card_title: "puffy smack",
    card_describe: "Son Direniş durumundaki rakibi atlayıp arkasındaki rakibi hedef alır",
    part_name: "cloud",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-08.png"
  },
  {
    class: "kuş",
    card_title: "cool breeze",
    card_describe: "Hedef rakibe 2 raunt için Soğuk efekti uygular",
    part_name: "grandma's fan",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-10.png"
  },
  {
    class: "kuş",
    card_title: "all-out shot",
    card_describe: "Bu axie kendisine %30 Can Puanı kadar hasar verir",
    part_name: "post fight",
    attack_type: "uzaktan",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bird-tail-12.png"
  },
  {
    class: "böcek",
    card_title: "sticky goo",
    card_describe: "Bu axienin kalkanı kırıldığında rakibe Sersem efekti uygular",
    part_name: "snail shell",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-back-02.png"
  },
  {
    class: "böcek",
    card_title: "barb strike",
    card_describe: "Zincirleme Saldırı yapıldığında rakibe Zehir efekti uygular",
    part_name: "garish worm",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-back-04.png"
  },
  {
    class: "böcek",
    card_title: "bug noise",
    card_describe: "Bu kartın kullanıldığı rakibin bir sonraki saldırısı için Negatif Saldırı efekti uygular",
    part_name: "buzz buzz",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-back-06.png"
  },
  {
    class: "böcek",
    card_title: "bug splat",
    card_describe: "Böcek sınıfı rakibe saldırırken %50 fazla hasar verir",
    part_name: "sandal",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-back-08.png"
  },
  {
    class: "böcek",
    card_title: "scarab curse",
    card_describe: "Hedef rakibin bir sonraki raunta kadar İyileşmesini engeller",
    part_name: "scarab",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-back-10.png"
  },
  {
    class: "böcek",
    card_title: "buzzing wind",
    card_describe: "Hedef rakibe Kırılgan efekti uygular",
    part_name: "spiky wing",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-back-12.png"
  },
  {
    class: "böcek",
    card_title: "mystic rush",
    card_describe: "Hedef rakibe 2 raunt için Negatif Hız efekti uygular",
    part_name: "laggin",
    attack_type: "yakından",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-horn-02.png"
  },
  {
    class: "böcek",
    card_title: "bug signal",
    card_describe: "Başka bir \"Bug Signal\" kartıyla Zincirleme Saldırı yapıldığında rakipten 1 enerji çalar",
    part_name: "antenna",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-horn-04.png"
  },
  {
    class: "böcek",
    card_title: "grub surprise",
    card_describe: "Hedef rakibin kalkanı varsa Korkak efekti uygular",
    part_name: "caterpillars",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-horn-06.png"
  },
  {
    class: "böcek",
    card_title: "dull grip",
    card_describe: "Hedef rakibin kalkanı varsa %30 fazla hasar verir",
    part_name: "pliers",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-horn-08.png"
  },
  {
    class: "böcek",
    card_title: "third glance",
    card_describe: "Rakibin elindeki kartlardan rastgele 1 tanesini yok eder",
    part_name: "parasite",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-horn-10.png"
  },
  {
    class: "böcek",
    card_title: "disguise",
    card_describe: "Bitki sınıfı bir kartla birlikte kullanıldığında 1 enerji alırsınız",
    part_name: "leaf bug",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-horn-12.png"
  },
  {
    class: "böcek",
    card_title: "blood taste",
    card_describe: "Axie kendini bu kartla rakibe verdiği hasar kadar iyileştirir",
    part_name: "mosquito",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-mouth-02.png"
  },
  {
    class: "böcek",
    card_title: "sunder claw",
    card_describe: "Rakibin elindeki kartlardan rastgele 1 tanesini yok eder",
    part_name: "pincer",
    attack_type: "yakından",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-mouth-04.png"
  },
  {
    class: "böcek",
    card_title: "terror chomp",
    card_describe: "Zincirleme Saldırı yapıldığında hedef rakibe 2 tur için Korkak efekti uygular",
    part_name: "cute bunny",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-mouth-08.png"
  },
  {
    class: "böcek",
    card_title: "mite bite",
    card_describe: "Başka bir kartla birlikte kullanıldığında %100 fazla hasar verir",
    part_name: "square teeth",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-mouth-10.png"
  },
  {
    class: "böcek",
    card_title: "chemical warfare",
    card_describe: "Rakibe raunt sonuna kadar Kokuşuk efekti uygular",
    part_name: "ant",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-tail-02.png"
  },
  {
    class: "böcek",
    card_title: "twin needle",
    card_describe: "Başka bir kartla birlikte kullanıldığında iki kere saldırır",
    part_name: "twin tail",
    attack_type: "uzaktan",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-tail-04.png"
  },
  {
    class: "böcek",
    card_title: "anesthetic bait",
    card_describe: "Bu axieye Balık veya Kuş sınıfı bir kartla saldırı yapıldığında rakibe Sersem efekti uygular. Her raunt sadece 1 kere tetiklenebilir.",
    part_name: "fish snack",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-tail-06.png"
  },
  {
    class: "böcek",
    card_title: "numbing lecretion",
    card_describe: "Hedef rakibin bir sonraki raunt için Yakından Saldırı kartlarını kullanmasını engeller",
    part_name: "gravel ant",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-tail-08.png"
  },
  {
    class: "böcek",
    card_title: "grub explode",
    card_describe: "Son Direniş durumunda kullanıldığında rakibe %100 fazla hasar verir ve bu axienin Son Direnişi biter",
    part_name: "pupae",
    attack_type: "yakından",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-tail-10.png"
  },
  {
    class: "böcek",
    card_title: "allergic reaction",
    card_describe: "Saldırdığı rakibin üzerinde herhangi bir Negatif efekt varsa %30 fazla hasar verir",
    part_name: "thorny caterpillar",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/bug-tail-12.png"
  },
  {
    class: "bitki",
    card_title: "turnip rocket",
    card_describe: "Bu kartın yanında en az 2 kart kullanıldığında Kuş sınıfı rakibi hedef alır",
    part_name: "turnip",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-02.png"
  },
  {
    class: "bitki",
    card_title: "shroom's grace",
    card_describe: "Bu axie kendini 120 Can Puanı iyileştirir",
    part_name: "shiitake",
    attack_type: "destek",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-04.png"
  },
  {
    class: "bitki",
    card_title: "cleanse scent",
    card_describe: "Üzerindeki tüm negatif efektleri siler",
    part_name: "bidens",
    attack_type: "destek",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-06.png"
  },
  {
    class: "bitki",
    card_title: "aqua stock",
    card_describe: "Bu axieye yapılan her Balık sınıfı saldırısı için 1 enerji alır",
    part_name: "watering can",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-08.png"
  },
  {
    class: "bitki",
    card_title: "refresh",
    card_describe: "Önündeki takım arkadaşının üzerindeki tüm negatif efektleri siler",
    part_name: "mint",
    attack_type: "destek",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-10.png"
  },
  {
    class: "bitki",
    card_title: "october treat",
    card_describe: "Kalkanı kırılmazsa 1 kart çekersiniz",
    part_name: "pumpkin",
    attack_type: "destek",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-back-12.png"
  },
  {
    class: "bitki",
    card_title: "bamboo clan",
    card_describe: "Zincirleme Saldırı yapıldığında %20 fazla hasar verir",
    part_name: "bamboo shoot",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-02.png"
  },
  {
    class: "bitki",
    card_title: "wooden stab",
    card_describe: "Kalkanı kırılırsa bu saldırı %20 fazla hasar verir",
    part_name: "beech",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-04.png"
  },
  {
    class: "bitki",
    card_title: "healing aroma",
    card_describe: "Bu axie kendini 120 Can Puanı iyileştirir",
    part_name: "rose bud",
    attack_type: "destek",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-06.png"
  },
  {
    class: "bitki",
    card_title: "sweet party",
    card_describe: "Önündeki takım arkadaşını 270 Can Puanı iyileştirir. Takım arkadaşı kalmadıysa kendini iyileştirir",
    part_name: "strawberry shortcake",
    attack_type: "destek",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-08.png"
  },
  {
    class: "bitki",
    card_title: "prickly trap",
    card_describe: "Bu axie en son oynuyorsa bu saldırı %20 fazla hasar verir",
    part_name: "cactus",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-10.png"
  },
  {
    class: "bitki",
    card_title: "seed bullet",
    card_describe: "En hızlı rakibi hedef alır",
    part_name: "watermelon",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-horn-12.png"
  },
  {
    class: "bitki",
    card_title: "vegetal bite",
    card_describe: "Başka bir kartla birlikte kullanıldığında rakipten 1 enerji çalar",
    part_name: "serious",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-mouth-02.png"
  },
  {
    class: "bitki",
    card_title: "drain bite",
    card_describe: "Axie kendini bu kartla rakibe verdiği hasar kadar iyileştirir",
    part_name: "zigzag",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-mouth-04.png"
  },
  {
    class: "bitki",
    card_title: "vegan diet",
    card_describe: "Axie kendini bu kartla Bitki sınıfı rakibe verdiği hasar kadar iyileştirir",
    part_name: "herbivore",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-mouth-08.png"
  },
  {
    class: "bitki",
    card_title: "forest spirit",
    card_describe: "Önündeki takım arkadaşını 190 Can Puanı iyileştirir",
    part_name: "silence whisper",
    attack_type: "destek",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-mouth-10.png"
  },
  {
    class: "bitki",
    card_title: "carrot hammer",
    card_describe: "Kalkanı kırıldığında 1 enerji alırsınız",
    part_name: "carrot",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-02.png"
  },
  {
    class: "bitki",
    card_title: "cattail slap",
    card_describe: "Bu axieye yapılan her Yabani, Böcek veya Meka sınıfı saldırısı için 1 kart çekersiniz",
    part_name: "cattail",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-04.png"
  },
  {
    class: "bitki",
    card_title: "leek leak",
    card_describe: "Saldırıya uğradığı zaman saldıran rakibin bir sonraki raunt Uzaktan Saldırı kartlarını kullanmasını engeller",
    part_name: "hatsune",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-06.png"
  },
  {
    class: "bitki",
    card_title: "gas unleash",
    card_describe: "Bu kartla saldırdığında ve saldırıya uğradığı her defa rakibe Zehir efekti uygular",
    part_name: "yam",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-08.png"
  },
  {
    class: "bitki",
    card_title: "aqua deflect",
    card_describe: "Balık sınıfı kartlarla yapılan saldırıları eğer varsa arkasındaki takım arkadaşına yönlendirir",
    part_name: "potato leaf",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-10.png"
  },
  {
    class: "bitki",
    card_title: "spicy surprise",
    card_describe: "Saldırdığı rakibin bir sonraki raunt Ağız kartını kullanmasını engeller",
    part_name: "hot butt",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/plant-tail-12.png"
  },
  {
    class: "sürüngen",
    card_title: "ivory chop",
    card_describe: "Kalkanı kırıldığında 1 kart çekersiniz",
    part_name: "bone sail",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-back-02.png"
  },
  {
    class: "sürüngen",
    card_title: "spike throw",
    card_describe: "Bu kartın yanında en az 2 kart kullanıldığında kalkanı en düşük rakibi hedef alır",
    part_name: "tri spikes",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-back-04.png"
  },
  {
    class: "sürüngen",
    card_title: "vine dagger",
    card_describe: "Bitki sınıfı bir kartla birlikte kullanıldığında bu kart %100 daha fazla kalkan verir",
    part_name: "green thorns",
    attack_type: "uzaktan",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-back-06.png"
  },
  {
    class: "sürüngen",
    card_title: "bulkwark",
    card_describe: "Rakibin Yakından Saldırılarıyla yaptığı hasarın %40ını rakibe geri yansıtır",
    part_name: "indian star",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-back-08.png"
  },
  {
    class: "sürüngen",
    card_title: "slippery shield",
    card_describe: "Yanındaki takım arkadaşları bu kartın verdiği kalkanın %15ini alır",
    part_name: "red ear",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-back-10.png"
  },
  {
    class: "sürüngen",
    card_title: "nile strike",
    card_describe: "Hedef rakibe 2 raunt için Negatif Hız efekti uygular",
    part_name: "croc",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-back-12.png"
  },
  {
    class: "sürüngen",
    card_title: "poo fling",
    card_describe: "Hedef rakibe raunt sonuna kadar Kokuşuk efekti uygular",
    part_name: "unko",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-horn-02.png"
  },
  {
    class: "sürüngen",
    card_title: "scaly lunge",
    card_describe: "Başka bir \"Lunge\" kartıyla Zincirleme Saldırı yapıldığında %20 fazla hasar verir",
    part_name: "scaly spear",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-horn-04.png"
  },
  {
    class: "sürüngen",
    card_title: "surprise invasion",
    card_describe: "Hedef rakip bu axieden hızlı ise %30 fazla hasar verir",
    part_name: "cerastes",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-horn-06.png"
  },
  {
    class: "sürüngen",
    card_title: "tiny catapult",
    card_describe: "Rakibin Uzaktan Saldırılarıyla yaptığı hasarın %50sini rakibe geri yansıtır",
    part_name: "scaly spoon",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-horn-08.png"
  },
  {
    class: "sürüngen",
    card_title: "disarm",
    card_describe: "Hedef rakibe 2 raunt için Negatif Hız efekti uygular",
    part_name: "incisor",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-horn-10.png"
  },
  {
    class: "sürüngen",
    card_title: "overgrow keratin",
    card_describe: "Bu axie bu kartın kullanıldığı raunt kullanılan her kart için 20 kalkan yeniler",
    part_name: "bumpy",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-horn-12.png"
  },
  {
    class: "sürüngen",
    card_title: "sneaky raid",
    card_describe: "En uzak rakibi hedef alır",
    part_name: "toothless bite",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-mouth-02.png"
  },
  {
    class: "sürüngen",
    card_title: "kotaro bite",
    card_describe: "Hedef rakip bu axieden hızlı ise 1 enerji alırsınız",
    part_name: "kotaro",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-mouth-04.png"
  },
  {
    class: "sürüngen",
    card_title: "why so serious",
    card_describe: "Axie kendini bu kartla Balık sınıfı rakibe verdiği hasar kadar iyileştirir",
    part_name: "razor bite",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-mouth-08.png"
  },
  {
    class: "sürüngen",
    card_title: "chomp",
    card_describe: "Bu kartın yanında en az 2 kart kullanıldığında rakibe Sersem efekti uygular",
    part_name: "tiny turtle",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-mouth-10.png"
  },
  {
    class: "sürüngen",
    card_title: "critical escape",
    card_describe: "Alınan hasarı %15 azaltır",
    part_name: "wall gecko",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-tail-02.png"
  },
  {
    class: "sürüngen",
    card_title: "scale dart",
    card_describe: "Hedef rakibin üzerinde herhangi bir Pozitif efekt varsa 1 enerji alırsınız",
    part_name: "iguana",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-tail-04.png"
  },
  {
    class: "sürüngen",
    card_title: "tiny swing",
    card_describe: "4. raunttan sonra %50 fazla hasar vermeye başlar",
    part_name: "tiny dino",
    attack_type: "yakından",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-tail-06.png"
  },
  {
    class: "sürüngen",
    card_title: "jar barrage",
    card_describe: "Bu axienin kalkanını kıran hasarın fazlası Can Puanına hasar vermez",
    part_name: "snake jar",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-tail-08.png"
  },
  {
    class: "sürüngen",
    card_title: "neuro toxin",
    card_describe: "Hedef rakibin üzerinde Zehir efekti varsa Negatif Saldırı efekti uygular",
    part_name: "gila",
    attack_type: "uzaktan",
    energy_cost: '1',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-tail-10.png"
  },
  {
    class: "sürüngen",
    card_title: "venom spray",
    card_describe: "Hedefe 2x Zehir efekti uygular",
    part_name: "grass snake",
    attack_type: "uzaktan",
    energy_cost: '0',
    damage: 0,
    shield: 0,
    icon_url: "",
    image_url: "https://storage.googleapis.com/axie-cdn/game/cards/base/reptile-tail-12.png"
  }
]

  constructor(){}

  list(){
    return this.data;
  }
}
